// packages/react/src/components/tag/Tag.tsx
/* eslint-disable react/prop-types */
import React, { FC, ReactChild } from 'react'
import { Color, DEFAULT_COLOR } from '@share/constants'
import '@share/components/tag/index.less'

type Props = {
  type?: Color
  filled?: boolean
  children: ReactChild
}
const Tag: FC<Props> = ({ type = DEFAULT_COLOR, children, filled }) => (
  <span
    className={['tag', type && `tag--${type}`, filled && `tag--${type}--filled`]
      .filter((name) => !!name)
      .join(' ')}
  >
    {children}
  </span>
)

export default Tag

// packages/vue/src/components/tag/Tag.vue
<template>
  <span
    :class="['tag', type && `tag--${type}`, filled && `tag--${type}--filled`]"
  >
    <slot></slot>
  </span>
</template>

<script lang="ts">
import { Color, DEFAULT_COLOR } from '@share/constants'
import { colorValidator } from '@share/validator'
import { defineComponent, PropType } from 'vue'
export default defineComponent({
  props: {
    type: {
      type: String as PropType<Color>,
      default: DEFAULT_COLOR,
      validator: colorValidator
    },
    closable: { type: Boolean },
    filled: { type: Boolean }
  }
})
</script>

<style scoped lang="less">
@import '@share/components/tag/index.less';
</style>
