// packages/vue/src/components/loading/Loading.vue
<template>
  <svg
    :class="loading"
    :style="{
      maxWidth: diameterPx,
      maxHeight: diameterPx
    }"
  >
    <circle
      :class="loadingCircle"
      :stroke="color"
      :stroke-width="stroke"
      stroke-linecap="round"
      fill="none"
      :r="normalizedRadius"
      :cx="radius"
      :cy="radius"
      :pathLength="PATH_LENGTH"
    />
  </svg>
</template>

<script lang="ts">
import {
  classNames,
  DEFAULT_COLOR,
  DEFAULT_RADIUS,
  DEFAULT_STROKE,
  PATH_LENGTH
} from '@share/components/loading/constants'
import { divide, multiply, px, subtract } from '@share/utils'
import { computed, defineComponent } from 'vue'

export default defineComponent({
  props: {
    stroke: {
      default: DEFAULT_STROKE,
      type: Number
    },
    radius: { default: DEFAULT_RADIUS, type: Number },
    color: { default: DEFAULT_COLOR, type: String }
  },
  setup(props) {
    const normalizedRadius = computed(() =>
      subtract(props.radius, divide(props.stroke, 2))
    )
    const diameter = computed<number>(() => multiply(props.radius, 2))
    const diameterPx = computed<string>(() => px(diameter.value.toString()))
    return { normalizedRadius, diameterPx, PATH_LENGTH, ...classNames }
  }
})
</script>

<style scoped lang="less">
@import '@share/components/loading/index.less';
</style>

// packages/react/src/components/loading/Loading.tsx
/* eslint-disable react/prop-types */
import React, { FC, useMemo } from 'react'
import '@share/components/loading/index.less'
import {
  DEFAULT_RADIUS,
  DEFAULT_STROKE,
  DEFAULT_COLOR,
  PATH_LENGTH,
  classNames
} from '@share/components/loading/constants'
import { divide, multiply, px, subtract } from '@share/utils'

type Props = Partial<{
  stroke: number
  radius: number
  color: string
}>

const Loading: FC<Props> = ({
  stroke = DEFAULT_STROKE,
  radius = DEFAULT_RADIUS,
  color = DEFAULT_COLOR
}) => {
  const normalizedRadius = useMemo(() => subtract(radius, divide(stroke, 2)), [
    radius,
    stroke
  ])
  const { loading, loadingCircle } = classNames
  const diameter = useMemo(() => multiply(radius, 2), [radius])
  const diameterpx = useMemo(() => px(diameter.toString()), [diameter])

  return (
    <svg
      className={loading}
      style={{
        maxWidth: diameterpx,
        maxHeight: diameterpx
      }}
    >
      <circle
        className={loadingCircle}
        stroke={color}
        strokeWidth={stroke}
        strokeLinecap="round"
        fill="none"
        r={normalizedRadius}
        cx={radius}
        cy={radius}
        pathLength={PATH_LENGTH}
      />
    </svg>
  )
}

export default Loading
